# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerank',
            name='entity',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='property',
            name='identifier',
            field=models.CharField(max_length=1024),
        ),
    ]
